### ISSUE TITLE
Error: Cannot find module '../socket.io-client/node_modules/engine.io-client/node_modules/xmlhttprequest'

### ISSUE THREAD

**Issue by Dexon95** [rakeshok/socket.io-client-cookie#7]
> module.js:442
>     throw err;
>     ^
> 
> Error: Cannot find module '../socket.io-client/node_modules/engine.io-client/node_modules/xmlhttprequest'

Had to manually install an older version of socket.io-client on the old npm version (which had the node_modules directory in it) to make socket.io-client-cookie working. 
Currently using node v6.2.0 (npm v3.8.9)

Also installed socket io client via `npm install --save socket.io-client`

**Comment by ecdeveloper** [comment]
Any updates here?

**Comment by ecdeveloper** [comment]
@rakeshok

**Comment by Dexon95** [comment]
@ecdeveloper I believe now socket.io has this cookie feature. This issue doesn't really matter anymore.

**Comment by ecdeveloper** [comment]
Does it, though? I couldn't find any info on that in their docs. The problem I'm currently getting is the following - I have a server app using `socket.io-client`. It connects fine to my socket.io server, but whenever I reconnect - the session id reset on the socket.io side. I'm trying to simulate a browser refresh behavior, where the connection gets re-established, but can't figure out why would my connection get a new session id. I thought it's a cookie related issue.

**Comment by diegobill** [comment]
Same problem, How can I set cookie using socket.io-client ???
