### ISSUE TITLE
No longer works with current `socket.io-client`

### ISSUE THREAD

**Issue by japsu** [rakeshok/socket.io-client-cookie#8]
The package used to implement `XMLHttpRequest` used by `engine.io-client` is nowadays `xmlhttprequest-ssl` instead of `xmlhttprequest` leading to

```
Error: Cannot find module '../socket.io-client/node_modules/engine.io-client/node_modules/xmlhttprequest
```

when trying to import `socket.io-client-cookie`.

```
├─ socket.io-client-cookie@0.1.0
├─ socket.io-client@1.7.3
│  ├─ backo2@1.0.2
│  ├─ component-bind@1.0.0
│  ├─ component-emitter@1.2.1
│  ├─ debug@2.3.3
│  ├─ engine.io-client@1.8.3
│  ├─ has-binary@0.1.7
│  ├─ indexof@0.0.1
│  ├─ object-component@0.0.3
│  ├─ parseuri@0.0.5
│  ├─ socket.io-parser@2.3.1
│  └─ to-array@0.1.4
```

**Comment by diegobill** [comment]
Cannot find module here too

**Comment by japsu** [comment]
I'm closing this and making another issue because this module is actually no longer necessary.

While this is very thinly documented, you can nowadays pass `extraHeaders` to the `io` constructor like this:

```javascript
const io = require('socket.io-client');

const socket = io(url, { path, extraHeaders: { cookie } });
```

Documented in the underlying `engine.io-client` library:

https://github.com/socketio/engine.io-client#nodejs-with-extraheaders

**Comment by japsu** [comment]
See #9

**Comment by diegobill** [comment]
@japsu , extraHeaders is not in socket.io-client API (https://github.com/socketio/socket.io-client/blob/master/docs/API.md), How can I set cookie to a instance of socket.io-client not instance of engine.io-client?

**Comment by japsu** [comment]
@diegobill, hence "thinly documented". You can try it yourself and verify that it indeed works.

As you can see here, `opts` is passed verbatim to `engine.io-client`:

https://github.com/socketio/socket.io-client/blob/2dcc794b8fc2c45956c6b798eb90cfd9c11e183c/lib/manager.js#L226

Edit: permalink to commit so that line number does not go off the trolley

**Comment by diegobill** [comment]
works, thanks

**Comment by japsu** [comment]
No problem. Might be inclined to put up a full example sometime soon to signal boost this little known fact.
